---
title: "TS_finalproject"
output: html_document
date: "2024-05-14"
---

# Data Importing
```{r}
data <- read.csv('baggagecomplaints.csv')
data$Date <- as.Date(paste(data$Year, data$Month, "01", sep = "-"))
```

```{r}
airlines <- unique(data$Airline)
airline_data_frames <- list()
for (airline in airlines) {
  airline_data_frames[[airline]] <- subset(data, Airline == airline)
}
```

```{r}
ae <- airline_data_frames[['American Eagle']]
haw <- airline_data_frames[['Hawaiian']]
uni <- airline_data_frames[['United']]
```


## American Eagle
```{r}
ae <- ae[, c("Date","Scheduled", "Cancelled", "Enplaned","Baggage")]

cutoff_date <- as.Date("2010-01-01")

Diff_Baggage_ae <- diff(ae$Baggage, differences = 1)
ae <- ae[-1, ]
ae$Diff_Baggage <- Diff_Baggage_ae

train_ae <- ae[ae$Date < cutoff_date, ]
valid_ae <- ae[ae$Date >= cutoff_date, ]


corr_ae <- cor(ae[, c("Scheduled", "Cancelled", "Enplaned","Baggage")], use = "complete.obs")
print(corr_ae)
```

```{r}
library(ggplot2)
library(reshape2)
plot_scheduled <- ggplot(ae, aes(x = Date, y = Scheduled)) +
  geom_line(color = "blue") +
  labs(title = "Scheduled Flights Over Time", x = "Date", y = "Scheduled Flights") +
  theme_minimal()

# Plot Cancelled
plot_cancelled <- ggplot(ae, aes(x = Date, y = Cancelled)) +
  geom_line(color = "red") +
  labs(title = "Cancelled Flights Over Time", x = "Date", y = "Cancelled Flights") +
  theme_minimal()

# Plot Enplaned
plot_enplaned <- ggplot(ae, aes(x = Date, y = Enplaned)) +
  geom_line(color = "green") +
  labs(title = "Enplaned Passengers Over Time", x = "Date", y = "Enplaned Passengers") +
  theme_minimal()

# Plot Baggage
plot_baggage <- ggplot(ae, aes(x = Date, y = Baggage)) +
  geom_line(color = "purple") +
  labs(title = "Baggage Per Enplaned Passenger Over Time", x = "Date", y = "Baggage Per Enplaned Passenger") +
  theme_minimal()

# Display the plots
print(plot_scheduled)
print(plot_cancelled)
print(plot_enplaned)
print(plot_baggage)
```


```{r}
acf_scheduled <- acf(ae$Scheduled, main = "ACF of Scheduled Flights")
acf_cancelled <- acf(ae$Cancelled, main = "ACF of Cancelled Flights")
acf_enplaned <- acf(ae$Enplaned, main = "ACF of Enplaned Passengers")
acf_baggage_per_enplaned <- acf(ae$Baggage, main = "ACF of Baggage")
acf_baggage_per_enplaned <- acf(ae$Diff_Baggage, main = "ACF of Diff_Baggage")
```

```{r}
library(tseries)

kpss <- kpss.test(ae$Diff_Baggage)
adf <- adf.test(ae$Diff_Baggage)

print(kpss)
print(adf)
```


### Model
```{r}
# Fit the linear model on the differenced Baggage variable
lm_ae <- lm(Diff_Baggage ~ Scheduled + Cancelled + Enplaned, data = train_ae)
print(summary(lm_ae))

residual_ae <- residuals(lm_ae)
plot(residual_ae,type = "o", main = "Residuals from Linear Model for American Eagle", ylab = "Residuals", xlab = "Observations")
abline(h=0, col = "Red")

acf(residual_ae,main = "ACF of LM residuals")
qqnorm(residual_ae)
qqline(residual_ae)

library(car)
ljung_box_arima <- Box.test(residual_ae, type = "Ljung-Box")
durbin_watson <- dwtest(lm_ae)

print(ljung_box_arima)
print(durbin_watson)
```
```{r}
xreg_ae <- cbind(train_ae$Scheduled, train_ae$Cancelled, train_ae$Enplaned)
dyn_ae <- auto.arima(train_ae$Diff_Baggage, xreg=xreg_ae)
summary(dyn_ae)

resid_dr_ae <- residuals(dyn_ae)
plot(resid_dr_ae,type = "o", main = "Residuals from Dynamic Regression for American Eagle", ylab = "Residuals", xlab = "Observations")
abline(h=0, col = "Red")

acf(resid_dr_ae,main = "ACF of LM with ARIMA residuals")
qqnorm(resid_dr_ae)
qqline(resid_dr_ae)

ljung_box_arima <- Box.test(resid_dr_ae, type = "Ljung-Box")

print(ljung_box_arima)
```

## Hawaiian
```{r}
haw <- haw[, c("Date","Scheduled", "Cancelled", "Enplaned","Baggage")]

cutoff_date <- as.Date("2010-01-01")
Diff_Baggage_haw <- diff(haw$Baggage, differences = 1)
haw <- haw[-1, ]
haw$Diff_Baggage <- Diff_Baggage_haw
train_haw <- haw[haw$Date < cutoff_date, ]
valid_haw <- haw[haw$Date >= cutoff_date, ]


corr_haw <- cor(haw[, c("Scheduled", "Cancelled", "Enplaned","Baggage")], use = "complete.obs")
print(corr_haw)
```

```{r}
plot_scheduled <- ggplot(haw, aes(x = Date, y = Scheduled)) +
  geom_line(color = "blue") +
  labs(title = "Scheduled Flights Over Time", x = "Date", y = "Scheduled Flights") +
  theme_minimal()

# Plot Cancelled
plot_cancelled <- ggplot(haw, aes(x = Date, y = Cancelled)) +
  geom_line(color = "red") +
  labs(title = "Cancelled Flights Over Time", x = "Date", y = "Cancelled Flights") +
  theme_minimal()

# Plot Enplaned
plot_enplaned <- ggplot(haw, aes(x = Date, y = Enplaned)) +
  geom_line(color = "green") +
  labs(title = "Enplaned Passengers Over Time", x = "Date", y = "Enplaned Passengers") +
  theme_minimal()

# Plot Baggage
plot_baggage <- ggplot(haw, aes(x = Date, y = Baggage)) +
  geom_line(color = "purple") +
  labs(title = "Baggage Per Enplaned Passenger Over Time", x = "Date", y = "Baggage Per Enplaned Passenger") +
  theme_minimal()

# Display the plots
print(plot_scheduled)
print(plot_cancelled)
print(plot_enplaned)
print(plot_baggage)
```

```{r}
acf_baggage_per_Baggage <- acf(haw$Baggage,lag=100, main = "ACF of Baggage")
```


```{r}
adf.test(uni$Baggage)
kpss.test(uni$Baggage)
```

### Model
```{r}
lm_haw <- lm(Diff_Baggage ~ Scheduled + Cancelled + Enplaned, data = train_haw)
print(summary(lm_haw))

residual_haw <- residuals(lm_haw)
plot(residual_haw,type = "o", main = "Residuals from Linear Model for Hawaiian", ylab = "Residuals", xlab = "Observations")
abline(h=0, col = "Red")

acf(residual_haw,main = "ACF of LM residuals")
qqnorm(residual_haw)
qqline(residual_haw)

ljung_box_arima <- Box.test(residual_haw, type = "Ljung-Box")
durbin_watson <- dwtest(lm_haw)

print(ljung_box_arima)
print(durbin_watson)
```


```{r}
xreg_haw <- cbind(train_haw$Scheduled, train_haw$Cancelled, train_haw$Enplaned)
dyn_haw <- auto.arima(train_haw$Diff_Baggage, xreg=xreg_haw)
summary(dyn_haw)

resid_dr_haw <- residuals(dyn_haw)
plot(resid_dr_haw,type = "o", main = "Residuals from Dynamic Regression for Hawaiian", ylab = "Residuals", xlab = "Observations")
abline(h=0, col = "Red")

acf(resid_dr_haw,main = "ACF of LM residuals")
qqnorm(resid_dr_haw)
qqline(resid_dr_haw)

ljung_box_arima <- Box.test(resid_dr_haw, type = "Ljung-Box")

print(ljung_box_arima)
```



## United
```{r}
uni <- uni[, c("Date","Scheduled", "Cancelled", "Enplaned","Baggage")]

cutoff_date <- as.Date("2010-01-01")
Diff_Baggage_uni <- diff(uni$Baggage, differences = 1)
uni <- uni[-1, ]
uni$Diff_Baggage <- Diff_Baggage_uni
train_uni <- uni[uni$Date < cutoff_date, ]
valid_uni <- uni[uni$Date >= cutoff_date, ]


corr_uni <- cor(uni[, c("Scheduled", "Cancelled", "Enplaned","Baggage")], use = "complete.obs")
print(corr_uni)
```

```{r}
acf_baggage_per_Baggage <- acf(uni$Baggage,lag=100, main = "ACF of Baggage")
```

```{r}
plot_scheduled <- ggplot(uni, aes(x = Date, y = Scheduled)) +
  geom_line(color = "blue") +
  labs(title = "Scheduled Flights Over Time", x = "Date", y = "Scheduled Flights") +
  theme_minimal()

# Plot Cancelled
plot_cancelled <- ggplot(uni, aes(x = Date, y = Cancelled)) +
  geom_line(color = "red") +
  labs(title = "Cancelled Flights Over Time", x = "Date", y = "Cancelled Flights") +
  theme_minimal()

# Plot Enplaned
plot_enplaned <- ggplot(uni, aes(x = Date, y = Enplaned)) +
  geom_line(color = "green") +
  labs(title = "Enplaned Passengers Over Time", x = "Date", y = "Enplaned Passengers") +
  theme_minimal()

# Plot Baggage
plot_baggage <- ggplot(uni, aes(x = Date, y = Baggage)) +
  geom_line(color = "purple") +
  labs(title = "Baggage Per Enplaned Passenger Over Time", x = "Date", y = "Baggage Per Enplaned Passenger") +
  theme_minimal()

# Display the plots
print(plot_scheduled)
print(plot_cancelled)
print(plot_enplaned)
print(plot_baggage)
```


### Model
```{r}
lm_uni <- lm(Diff_Baggage ~ Scheduled + Cancelled + Enplaned, data = train_uni)
print(summary(lm_uni))

residual_uni <- residuals(lm_uni)
plot(residual_uni,type = "o", main = "Residuals from Linear Model for United", ylab = "Residuals", xlab = "Observations")
abline(h=0, col = "Red")

acf(residual_uni,main = "ACF of LM residuals")
qqnorm(residual_uni)
qqline(residual_uni)

ljung_box_arima <- Box.test(residual_uni, type = "Ljung-Box")
durbin_watson <- dwtest(lm_uni)

print(ljung_box_arima)
print(durbin_watson)
```


```{r}
xreg_uni <- cbind(train_uni$Scheduled, train_uni$Cancelled, train_uni$Enplaned)
dyn_uni <- auto.arima(train_uni$Diff_Baggage, xreg=xreg_uni)
summary(dyn_uni)

resid_dr_uni <- residuals(dyn_uni)
plot(resid_dr_uni,type = "o", main = "Residuals from Dynamic Regression for United", ylab = "Residuals", xlab = "Observations")
abline(h=0, col = "Red")

acf(resid_dr_uni,main = "ACF of LM residuals")
qqnorm(resid_dr_uni)
qqline(resid_dr_uni)

ljung_box_arima <- Box.test(resid_dr_uni, type = "Ljung-Box")

print(ljung_box_arima)
```
# Evaluation

## AE

```{r}
xreg_valid_ae <- cbind(valid_ae$Scheduled, valid_ae$Cancelled, valid_ae$Enplaned)

# Predict using the models
diff_pred_arima_ae <- forecast(dyn_ae, xreg = xreg_valid_ae)
diff_pred_lm_ae <- predict(lm_ae, newdata = valid_ae, interval = "confidence")

# Initialize vectors for cumulative predictions
predictions_arima_ae <- numeric(length(diff_pred_arima_ae$mean))
predictions_lm_ae <- numeric(length(diff_pred_lm_ae[, "fit"]))

# The last observed value in the training set
last_train_value <- tail(train_ae$Baggage, 1)

# Compute the cumulative predictions
predictions_arima_ae[1] <- last_train_value + diff_pred_arima_ae$mean[1]
predictions_lm_ae[1] <- last_train_value + diff_pred_lm_ae[1, "fit"]

for (i in 2:length(diff_pred_arima_ae$mean)) {
  predictions_arima_ae[i] <- predictions_arima_ae[i-1] + diff_pred_arima_ae$mean[i]
  predictions_lm_ae[i] <- predictions_lm_ae[i-1] + diff_pred_lm_ae[i, "fit"]
}
```



```{r}

library(Metrics)

# Evaluate ARIMA Model
mae_arima <- mae(valid_ae$Baggage, predictions_arima_ae)
mse_arima <- mse(valid_ae$Baggage, predictions_arima_ae)
rmse_arima <- sqrt(mse_arima)  # Calculating RMSE
mape_arima <- mean(abs((predictions_arima_ae - valid_ae$Baggage) / valid_ae$Baggage)) * 100

# Evaluate Linear Model
mae_lm <- mae(valid_ae$Baggage, predictions_lm_ae)
mse_lm <- mse(valid_ae$Baggage, predictions_lm_ae)
rmse_lm <- sqrt(mse_lm)  # Calculating RMSE
mape_lm <- mean(abs((predictions_lm_ae - valid_ae$Baggage) / valid_ae$Baggage)) * 100

# Print the results
# Assuming you've calculated MAE, MSE, and RMSE as shown before
evaluation_table <- data.frame(
  Model = c("ARIMA", "Linear Regression"),
  MAE = c(mae_arima, mae_lm),
  MSE = c(mse_arima, mse_lm),
  RMSE = c(rmse_arima, rmse_lm),
  MAPE = c(mape_arima,mape_lm)
)

library(knitr)
kable(evaluation_table, caption = "Performance Evaluation of Models", align = 'c')
```

## Hawaiian
```{r}
xreg_valid_haw <- cbind(valid_haw$Scheduled, valid_haw$Cancelled, valid_haw$Enplaned)

# Predict using the models
diff_pred_arima_haw <- forecast(dyn_haw, xreg = xreg_valid_haw)
diff_pred_lm_haw <- predict(lm_haw, newdata = valid_haw, interval = "confidence")

# Initialize vectors for cumulative predictions
predictions_arima_haw <- numeric(length(diff_pred_arima_haw$mean))
predictions_lm_haw <- numeric(length(diff_pred_lm_haw[, "fit"]))

# The last observed value in the training set
last_train_value <- tail(train_haw$Baggage, 1)

# Compute the cumulative predictions
predictions_arima_haw[1] <- last_train_value + diff_pred_arima_haw$mean[1]
predictions_lm_haw[1] <- last_train_value + diff_pred_lm_haw[1, "fit"]

for (i in 2:length(diff_pred_arima_haw$mean)) {
  predictions_arima_haw[i] <- predictions_arima_haw[i-1] + diff_pred_arima_haw$mean[i]
  predictions_lm_haw[i] <- predictions_lm_haw[i-1] + diff_pred_lm_haw[i, "fit"]
}
```

```{r}

library(Metrics)

# Evaluate ARIMA Model
mae_arima <- mae(valid_haw$Baggage, predictions_arima_haw)
mse_arima <- mse(valid_haw$Baggage, predictions_arima_haw)
rmse_arima <- sqrt(mse_arima)
mape_arima <- mean(abs((predictions_arima_haw - valid_haw$Baggage) / valid_haw$Baggage)) * 100

# Evaluate Linear Model
mae_lm <- mae(valid_haw$Baggage, predictions_lm_haw)
mse_lm <- mse(valid_haw$Baggage, predictions_lm_haw)
rmse_lm <- sqrt(mse_lm)  # Calculating RMSE
mape_lm <- mean(abs((predictions_lm_haw - valid_haw$Baggage) / valid_haw$Baggage)) * 100

# Print the results
# Assuming you've calculated MAE, MSE, and RMSE as shown before
evaluation_table <- data.frame(
  Model = c("ARIMA", "Linear Regression"),
  MAE = c(mae_arima, mae_lm),
  MSE = c(mse_arima, mse_lm),
  RMSE = c(rmse_arima, rmse_lm),
  MAPE = c(mape_arima,mape_lm)
)

library(knitr)
kable(evaluation_table, caption = "Performance Evaluation of Models", align = 'c')
```


## United
```{r}
xreg_valid_uni <- cbind(valid_uni$Scheduled, valid_uni$Cancelled, valid_uni$Enplaned)

# Predict using the models
diff_pred_arima_uni <- forecast(dyn_uni, xreg = xreg_valid_uni)
diff_pred_lm_uni <- predict(lm_uni, newdata = valid_uni, interval = "confidence")

# Initialize vectors for cumulative predictions
predictions_arima_uni <- numeric(length(diff_pred_arima_uni$mean))
predictions_lm_uni <- numeric(length(diff_pred_lm_uni[, "fit"]))

# The last observed value in the training set
last_train_value <- tail(train_uni$Baggage, 1)

# Compute the cumulative predictions
predictions_arima_uni[1] <- last_train_value + diff_pred_arima_uni$mean[1]
predictions_lm_uni[1] <- last_train_value + diff_pred_lm_uni[1, "fit"]

for (i in 2:length(diff_pred_arima_uni$mean)) {
  predictions_arima_uni[i] <- predictions_arima_uni[i-1] + diff_pred_arima_uni$mean[i]
  predictions_lm_uni[i] <- predictions_lm_uni[i-1] + diff_pred_lm_uni[i, "fit"]
}
```


```{r}

library(Metrics)

# Evaluate ARIMA Model
mae_arima <- mae(valid_uni$Baggage, predictions_arima_uni)
mse_arima <- mse(valid_uni$Baggage, predictions_arima_uni)
rmse_arima <- sqrt(mse_arima) 
mape_arima <- mean(abs((predictions_arima_uni - valid_uni$Baggage) / valid_uni$Baggage)) * 100

# Evaluate Linear Model
mae_lm <- mae(valid_uni$Baggage, predictions_lm_uni)
mse_lm <- mse(valid_uni$Baggage, predictions_lm_uni)
rmse_lm <- sqrt(mse_lm)  # Calculating RMSE
mape_lm <- mean(abs((predictions_lm_uni - valid_uni$Baggage) / valid_uni$Baggage)) * 100

# Print the results
evaluation_table <- data.frame(
  Model = c("ARIMA", "Linear Regression"),
  MAE = c(mae_arima, mae_lm),
  MSE = c(mse_arima, mse_lm),
  RMSE = c(rmse_arima, rmse_lm),
  MAPE = c(mape_arima,mape_lm)
)

library(knitr)
kable(evaluation_table, caption = "Performance Evaluation of Models", align = 'c')
```




